# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Qʼeqchiʼ spellchecker"
kek = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Qʼeqchiʼ, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
kek = "TRANSLATE: A spellchecker for Qʼeqchiʼ, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.kek"

[windows]
system_product_code = "{82C5936A-B64B-4F4A-9182-D718A72E6FD4}_is1"
legacy_product_codes = [
    { value = "5A343EE8-9067-4A3E-973B-D4A0A89C4670", kind = "nsis" },
    { value = "DE7DBDE6-A14D-4C96-9933-0766DC25A840", kind = "nsis" }
]
[package.speller]
name = "Qʼeqchiʼ"
version = "0.1.1"

[package.grammar]
name = "Qʼeqchiʼ"
version = "0.1.0"

[package.tts-textproc]
name = "Qʼeqchiʼ"
version = "0.1.0"

[package.hyphenator]
name = "Kekchí"
version = "0.1.0"
