template = "https://github.com/giellalt/template-lang-und"
rev_id = 86
template_sha = "4a78cd012dba1e807265878e7d466bbeea184194"

[replacements]
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekch√≠"
__UND__ = "kek"
