template = "https://github.com/giellalt/template-lang-und"
rev_id = 165
template_sha = "e90d50ced16049c0fd339de88458c3e44708f347"

[replacements]
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekch√≠"
__UND__ = "kek"
