template = "https://github.com/giellalt/template-lang-und"
rev_id = 137
template_sha = "802fd8b83bce294556e943c19a2dbfbeab559298"

[replacements]
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekch√≠"
__UND__ = "kek"
