template = "https://github.com/giellalt/template-lang-und"
rev_id = 246
template_sha = "b7ba420a949cf8ed3ed70f3b25c8a69c42d2e07f"

[replacements]
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekch√≠"
__UND__ = "kek"
__GLOTTOLOG_ID__ = "kekc1242"
