template = "https://github.com/giellalt/template-lang-und"
rev_id = 199
template_sha = "d70a79cf8d0a7f18b748087169a142781570f841"

[replacements]
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekch√≠"
__UND__ = "kek"
